import type { FloatingMarketLevelConfig } from './types';

/**
 * 30 levels of Floating Market
 * 
 * Level 1-3:   Obstacle dodge only (slow boat, no questions)
 * Level 4-9:   Simple orders — identify/addition (2-3 options)
 * Level 10:    Speed dodge — fast boat, no questions
 * Level 11-19: Change/subtraction questions (2-3 options)
 * Level 20:    Obstacle gauntlet — slow boat, lots of obstacles
 * Level 21-30: Mixed operations — addition, subtraction, multiplication (3 options)
 */
export const FLOATING_MARKET_LEVELS: Record<number, FloatingMarketLevelConfig> = {
    // === OBSTACLE ONLY (Levels 1-3) ===
    1: {
        level: 1,
        boatSpeed: 80,
        riverWidthRatio: 0.75,
        obstacleFrequency: 3.5,
        encounterCount: 0,
        questionType: 'none',
        optionCount: 0,
        coinFrequency: 4,
        difficultyMultiplier: 0.5,
        parTimeSeconds: 30,
        timeLimitSeconds: 60,
    },
    2: {
        level: 2,
        boatSpeed: 90,
        riverWidthRatio: 0.72,
        obstacleFrequency: 3.0,
        encounterCount: 0,
        questionType: 'none',
        optionCount: 0,
        coinFrequency: 3.5,
        difficultyMultiplier: 0.6,
        parTimeSeconds: 35,
        timeLimitSeconds: 65,
    },
    3: {
        level: 3,
        boatSpeed: 100,
        riverWidthRatio: 0.70,
        obstacleFrequency: 2.5,
        encounterCount: 0,
        questionType: 'none',
        optionCount: 0,
        coinFrequency: 3,
        difficultyMultiplier: 0.7,
        parTimeSeconds: 35,
        timeLimitSeconds: 65,
    },

    // === SIMPLE ORDERS — Identify / Addition (Levels 4-9) ===
    4: {
        level: 4,
        boatSpeed: 80,
        riverWidthRatio: 0.75,
        obstacleFrequency: 4.0,
        encounterCount: 5,
        questionType: 'identify',
        optionCount: 2,
        coinFrequency: 5,
        difficultyMultiplier: 0.8,
        parTimeSeconds: 60,
        timeLimitSeconds: 120,
    },
    5: {
        level: 5,
        boatSpeed: 85,
        riverWidthRatio: 0.73,
        obstacleFrequency: 3.8,
        encounterCount: 5,
        questionType: 'identify',
        optionCount: 2,
        coinFrequency: 5,
        difficultyMultiplier: 0.85,
        parTimeSeconds: 60,
        timeLimitSeconds: 120,
    },
    6: {
        level: 6,
        boatSpeed: 85,
        riverWidthRatio: 0.73,
        obstacleFrequency: 3.5,
        encounterCount: 6,
        questionType: 'addition',
        optionCount: 2,
        coinFrequency: 4.5,
        difficultyMultiplier: 0.9,
        parTimeSeconds: 70,
        timeLimitSeconds: 130,
    },
    7: {
        level: 7,
        boatSpeed: 90,
        riverWidthRatio: 0.70,
        obstacleFrequency: 3.5,
        encounterCount: 6,
        questionType: 'addition',
        optionCount: 2,
        coinFrequency: 4.5,
        difficultyMultiplier: 0.95,
        parTimeSeconds: 70,
        timeLimitSeconds: 130,
    },
    8: {
        level: 8,
        boatSpeed: 90,
        riverWidthRatio: 0.70,
        obstacleFrequency: 3.2,
        encounterCount: 7,
        questionType: 'addition',
        optionCount: 3,
        coinFrequency: 4,
        difficultyMultiplier: 1.0,
        parTimeSeconds: 80,
        timeLimitSeconds: 140,
    },
    9: {
        level: 9,
        boatSpeed: 95,
        riverWidthRatio: 0.68,
        obstacleFrequency: 3.0,
        encounterCount: 7,
        questionType: 'addition',
        optionCount: 3,
        coinFrequency: 4,
        difficultyMultiplier: 1.0,
        parTimeSeconds: 80,
        timeLimitSeconds: 140,
    },

    // === SPEED DODGE (Level 10) ===
    10: {
        level: 10,
        boatSpeed: 160,
        riverWidthRatio: 0.65,
        obstacleFrequency: 1.5,
        encounterCount: 0,
        questionType: 'none',
        optionCount: 0,
        coinFrequency: 2,
        difficultyMultiplier: 1.0,
        parTimeSeconds: 30,
        timeLimitSeconds: 50,
    },

    // === CHANGE / SUBTRACTION (Levels 11-19) ===
    11: {
        level: 11,
        boatSpeed: 85,
        riverWidthRatio: 0.72,
        obstacleFrequency: 4.0,
        encounterCount: 5,
        questionType: 'change',
        optionCount: 2,
        coinFrequency: 5,
        difficultyMultiplier: 1.0,
        parTimeSeconds: 70,
        timeLimitSeconds: 130,
    },
    12: {
        level: 12,
        boatSpeed: 90,
        riverWidthRatio: 0.70,
        obstacleFrequency: 3.8,
        encounterCount: 5,
        questionType: 'change',
        optionCount: 2,
        coinFrequency: 5,
        difficultyMultiplier: 1.05,
        parTimeSeconds: 70,
        timeLimitSeconds: 130,
    },
    13: {
        level: 13,
        boatSpeed: 90,
        riverWidthRatio: 0.70,
        obstacleFrequency: 3.5,
        encounterCount: 6,
        questionType: 'change',
        optionCount: 2,
        coinFrequency: 4.5,
        difficultyMultiplier: 1.1,
        parTimeSeconds: 75,
        timeLimitSeconds: 135,
    },
    14: {
        level: 14,
        boatSpeed: 95,
        riverWidthRatio: 0.68,
        obstacleFrequency: 3.5,
        encounterCount: 6,
        questionType: 'change',
        optionCount: 3,
        coinFrequency: 4.5,
        difficultyMultiplier: 1.1,
        parTimeSeconds: 80,
        timeLimitSeconds: 140,
    },
    15: {
        level: 15,
        boatSpeed: 95,
        riverWidthRatio: 0.68,
        obstacleFrequency: 3.2,
        encounterCount: 7,
        questionType: 'change',
        optionCount: 3,
        coinFrequency: 4,
        difficultyMultiplier: 1.15,
        parTimeSeconds: 85,
        timeLimitSeconds: 145,
    },
    16: {
        level: 16,
        boatSpeed: 100,
        riverWidthRatio: 0.66,
        obstacleFrequency: 3.0,
        encounterCount: 7,
        questionType: 'change',
        optionCount: 3,
        coinFrequency: 4,
        difficultyMultiplier: 1.15,
        parTimeSeconds: 85,
        timeLimitSeconds: 145,
    },
    17: {
        level: 17,
        boatSpeed: 100,
        riverWidthRatio: 0.66,
        obstacleFrequency: 2.8,
        encounterCount: 8,
        questionType: 'change',
        optionCount: 3,
        coinFrequency: 3.5,
        difficultyMultiplier: 1.2,
        parTimeSeconds: 90,
        timeLimitSeconds: 150,
    },
    18: {
        level: 18,
        boatSpeed: 105,
        riverWidthRatio: 0.64,
        obstacleFrequency: 2.8,
        encounterCount: 8,
        questionType: 'change',
        optionCount: 3,
        coinFrequency: 3.5,
        difficultyMultiplier: 1.2,
        parTimeSeconds: 90,
        timeLimitSeconds: 150,
    },
    19: {
        level: 19,
        boatSpeed: 110,
        riverWidthRatio: 0.64,
        obstacleFrequency: 2.5,
        encounterCount: 8,
        questionType: 'change',
        optionCount: 3,
        coinFrequency: 3,
        difficultyMultiplier: 1.25,
        parTimeSeconds: 95,
        timeLimitSeconds: 155,
    },

    // === OBSTACLE GAUNTLET (Level 20) ===
    20: {
        level: 20,
        boatSpeed: 90,
        riverWidthRatio: 0.60,
        obstacleFrequency: 1.2,
        encounterCount: 0,
        questionType: 'none',
        optionCount: 0,
        coinFrequency: 2,
        difficultyMultiplier: 1.2,
        parTimeSeconds: 40,
        timeLimitSeconds: 70,
    },

    // === MIXED OPERATIONS (Levels 21-30) ===
    21: {
        level: 21,
        boatSpeed: 95,
        riverWidthRatio: 0.68,
        obstacleFrequency: 3.5,
        encounterCount: 6,
        questionType: 'mixed',
        optionCount: 3,
        coinFrequency: 4,
        difficultyMultiplier: 1.2,
        parTimeSeconds: 85,
        timeLimitSeconds: 145,
    },
    22: {
        level: 22,
        boatSpeed: 100,
        riverWidthRatio: 0.66,
        obstacleFrequency: 3.2,
        encounterCount: 7,
        questionType: 'mixed',
        optionCount: 3,
        coinFrequency: 4,
        difficultyMultiplier: 1.25,
        parTimeSeconds: 90,
        timeLimitSeconds: 150,
    },
    23: {
        level: 23,
        boatSpeed: 100,
        riverWidthRatio: 0.66,
        obstacleFrequency: 3.0,
        encounterCount: 7,
        questionType: 'mixed',
        optionCount: 3,
        coinFrequency: 3.5,
        difficultyMultiplier: 1.25,
        parTimeSeconds: 90,
        timeLimitSeconds: 150,
    },
    24: {
        level: 24,
        boatSpeed: 105,
        riverWidthRatio: 0.64,
        obstacleFrequency: 2.8,
        encounterCount: 8,
        questionType: 'mixed',
        optionCount: 3,
        coinFrequency: 3.5,
        difficultyMultiplier: 1.3,
        parTimeSeconds: 95,
        timeLimitSeconds: 155,
    },
    25: {
        level: 25,
        boatSpeed: 105,
        riverWidthRatio: 0.64,
        obstacleFrequency: 2.5,
        encounterCount: 8,
        questionType: 'mixed',
        optionCount: 3,
        coinFrequency: 3,
        difficultyMultiplier: 1.3,
        parTimeSeconds: 95,
        timeLimitSeconds: 155,
    },
    26: {
        level: 26,
        boatSpeed: 110,
        riverWidthRatio: 0.62,
        obstacleFrequency: 2.5,
        encounterCount: 8,
        questionType: 'mixed',
        optionCount: 3,
        coinFrequency: 3,
        difficultyMultiplier: 1.35,
        parTimeSeconds: 100,
        timeLimitSeconds: 160,
    },
    27: {
        level: 27,
        boatSpeed: 110,
        riverWidthRatio: 0.62,
        obstacleFrequency: 2.2,
        encounterCount: 9,
        questionType: 'mixed',
        optionCount: 3,
        coinFrequency: 3,
        difficultyMultiplier: 1.35,
        parTimeSeconds: 100,
        timeLimitSeconds: 160,
    },
    28: {
        level: 28,
        boatSpeed: 115,
        riverWidthRatio: 0.60,
        obstacleFrequency: 2.0,
        encounterCount: 9,
        questionType: 'mixed',
        optionCount: 3,
        coinFrequency: 2.5,
        difficultyMultiplier: 1.4,
        parTimeSeconds: 105,
        timeLimitSeconds: 165,
    },
    29: {
        level: 29,
        boatSpeed: 120,
        riverWidthRatio: 0.58,
        obstacleFrequency: 2.0,
        encounterCount: 10,
        questionType: 'mixed',
        optionCount: 3,
        coinFrequency: 2.5,
        difficultyMultiplier: 1.4,
        parTimeSeconds: 110,
        timeLimitSeconds: 170,
    },
    30: {
        level: 30,
        boatSpeed: 125,
        riverWidthRatio: 0.55,
        obstacleFrequency: 1.8,
        encounterCount: 10,
        questionType: 'mixed',
        optionCount: 3,
        coinFrequency: 2,
        difficultyMultiplier: 1.5,
        parTimeSeconds: 115,
        timeLimitSeconds: 180,
    },
};
