export interface TaxiDriverLevelConfig {
    level: number;
    carSpeed: number;          // Pixels per second
    mapRotation: 0 | 90 | 180 | 270;  // Initial map rotation (car perspective)
    pathLength: number;        // Number of turns in the route
    decisionTimeMs: number;    // Time allowed to make a decision at intersection

    // Path Fade Mechanic (Levels 8+)
    pathFadeEnabled: boolean;
    pathFadeDelayMs: number;   // Delay before fade starts
    pathFadeDurationMs: number; // How long path stays hidden
    pathFadeInterval: number;  // 0 = one-time, >0 = recurring fade every N ms

    // Road Closure Mechanic (Levels 16+)
    roadClosureEnabled: boolean;
    roadClosureCount: number;  // Number of route changes during level

    // Brake Stop Mechanic - car randomly stops, player must press Forward
    brakeStopEnabled: boolean;
    brakeStopCount: number;    // Number of brake stops per level
    brakeStopTimeMs: number;   // Time allowed to press Forward

    // Stage/Portal System - multiple mini-maps per level
    stageCount: number;        // Number of stages (mini-maps) per level (1-5)

    // Button Swapping Mechanic (Levels 21+)
    swapControls?: boolean;

    difficultyMultiplier: number;
}

export const TAXIDRIVER_LEVELS: { [key: number]: TaxiDriverLevelConfig } = {
    // === TUTORIAL (Level 0) ===
    0: {
        level: 0,
        carSpeed: 60,
        mapRotation: 0,
        pathLength: 3,
        decisionTimeMs: 5000,
        pathFadeEnabled: false,
        pathFadeDelayMs: 0,
        pathFadeDurationMs: 0,
        pathFadeInterval: 0,
        roadClosureEnabled: false,
        roadClosureCount: 0,
        brakeStopEnabled: true,
        brakeStopCount: 1,
        brakeStopTimeMs: 4000,
        stageCount: 1,
        swapControls: false,
        difficultyMultiplier: 1.0
    },

    // === CHAPTER 1: BASIC DRIVING (Levels 1-3) ===
    // Bottom to top, simple paths
    1: {
        level: 1,
        carSpeed: 40,  // Reduced from 70 for mobile playability
        mapRotation: 0,
        pathLength: 4,
        decisionTimeMs: 4000,
        pathFadeEnabled: false,
        pathFadeDelayMs: 0,
        pathFadeDurationMs: 0,
        pathFadeInterval: 0,
        roadClosureEnabled: false,
        roadClosureCount: 0,
        brakeStopEnabled: true,
        brakeStopCount: 2,
        brakeStopTimeMs: 3500,
        stageCount: 1,
        difficultyMultiplier: 1.0
    },
    2: {
        level: 2,
        carSpeed: 45,  // Reduced from 80
        mapRotation: 0,
        pathLength: 5,
        decisionTimeMs: 3800,
        pathFadeEnabled: false,
        pathFadeDelayMs: 0,
        pathFadeDurationMs: 0,
        pathFadeInterval: 0,
        roadClosureEnabled: false,
        roadClosureCount: 0,
        brakeStopEnabled: true,
        brakeStopCount: 2,
        brakeStopTimeMs: 3200,
        stageCount: 1,
        difficultyMultiplier: 1.05
    },
    3: {
        level: 3,
        carSpeed: 50,  // Reduced from 90
        mapRotation: 0,
        pathLength: 6,
        decisionTimeMs: 3500,
        pathFadeEnabled: false,
        pathFadeDelayMs: 0,
        pathFadeDurationMs: 0,
        pathFadeInterval: 0,
        roadClosureEnabled: false,
        roadClosureCount: 0,
        brakeStopEnabled: true,
        brakeStopCount: 2,
        brakeStopTimeMs: 3000,
        stageCount: 1,
        difficultyMultiplier: 1.1
    },

    // === CHAPTER 2: MAP ROTATIONS (Levels 4-7) ===
    // Different starting positions/rotations
    4: {
        level: 4,
        carSpeed: 50,  // Reduced from 85
        mapRotation: 90,
        pathLength: 5,
        decisionTimeMs: 3500,
        pathFadeEnabled: false,
        pathFadeDelayMs: 0,
        pathFadeDurationMs: 0,
        pathFadeInterval: 0,
        roadClosureEnabled: false,
        roadClosureCount: 0,
        brakeStopEnabled: true,
        brakeStopCount: 1,
        brakeStopTimeMs: 3000,
        stageCount: 1,
        difficultyMultiplier: 1.15
    },
    5: {
        level: 5,
        carSpeed: 55,  // Reduced from 90
        mapRotation: 180,
        pathLength: 6,
        decisionTimeMs: 3300,
        pathFadeEnabled: false,
        pathFadeDelayMs: 0,
        pathFadeDurationMs: 0,
        pathFadeInterval: 0,
        roadClosureEnabled: false,
        roadClosureCount: 0,
        brakeStopEnabled: true,
        brakeStopCount: 1,
        brakeStopTimeMs: 2800,
        stageCount: 1,
        difficultyMultiplier: 1.2
    },
    6: {
        level: 6,
        carSpeed: 95,
        mapRotation: 270,
        pathLength: 6,
        decisionTimeMs: 3200,
        pathFadeEnabled: false,
        pathFadeDelayMs: 0,
        pathFadeDurationMs: 0,
        pathFadeInterval: 0,
        roadClosureEnabled: false,
        roadClosureCount: 0,
        brakeStopEnabled: true,
        brakeStopCount: 2,
        brakeStopTimeMs: 2700,
        stageCount: 2,
        difficultyMultiplier: 1.25
    },
    7: {
        level: 7,
        carSpeed: 100,
        mapRotation: 90,
        pathLength: 7,
        decisionTimeMs: 3000,
        pathFadeEnabled: false,
        pathFadeDelayMs: 0,
        pathFadeDurationMs: 0,
        pathFadeInterval: 0,
        roadClosureEnabled: false,
        roadClosureCount: 0,
        brakeStopEnabled: true,
        brakeStopCount: 2,
        brakeStopTimeMs: 2500,
        stageCount: 2,
        difficultyMultiplier: 1.3
    },

    // === CHAPTER 3: PATH GLITCH (Levels 8-10) ===
    // Back to bottom-top but path fades temporarily
    8: {
        level: 8,
        carSpeed: 85,
        mapRotation: 0,
        pathLength: 5,
        decisionTimeMs: 3500,
        pathFadeEnabled: true,
        pathFadeDelayMs: 3000,
        pathFadeDurationMs: 2000,
        pathFadeInterval: 0,
        roadClosureEnabled: false,
        roadClosureCount: 0,
        brakeStopEnabled: true,
        brakeStopCount: 1,
        brakeStopTimeMs: 2800,
        stageCount: 2,
        difficultyMultiplier: 1.3
    },
    9: {
        level: 9,
        carSpeed: 90,
        mapRotation: 0,
        pathLength: 6,
        decisionTimeMs: 3200,
        pathFadeEnabled: true,
        pathFadeDelayMs: 2500,
        pathFadeDurationMs: 2500,
        pathFadeInterval: 0,
        roadClosureEnabled: false,
        roadClosureCount: 0,
        brakeStopEnabled: true,
        brakeStopCount: 1,
        brakeStopTimeMs: 2600,
        stageCount: 2,
        difficultyMultiplier: 1.35
    },
    10: {
        level: 10,
        carSpeed: 95,
        mapRotation: 0,
        pathLength: 7,
        decisionTimeMs: 3000,
        pathFadeEnabled: true,
        pathFadeDelayMs: 2000,
        pathFadeDurationMs: 3000,
        pathFadeInterval: 6000,
        roadClosureEnabled: false,
        roadClosureCount: 0,
        brakeStopEnabled: true,
        brakeStopCount: 2,
        brakeStopTimeMs: 2500,
        stageCount: 2,
        difficultyMultiplier: 1.4
    },

    // === CHAPTER 4: FADE + ROTATION (Levels 11-15) ===
    11: {
        level: 11,
        carSpeed: 90,
        mapRotation: 90,
        pathLength: 6,
        decisionTimeMs: 3200,
        pathFadeEnabled: true,
        pathFadeDelayMs: 3000,
        pathFadeDurationMs: 2000,
        pathFadeInterval: 0,
        roadClosureEnabled: false,
        roadClosureCount: 0,
        brakeStopEnabled: true,
        brakeStopCount: 1,
        brakeStopTimeMs: 2500,
        stageCount: 3,
        difficultyMultiplier: 1.4
    },
    12: {
        level: 12,
        carSpeed: 95,
        mapRotation: 180,
        pathLength: 6,
        decisionTimeMs: 3000,
        pathFadeEnabled: true,
        pathFadeDelayMs: 2500,
        pathFadeDurationMs: 2500,
        pathFadeInterval: 0,
        roadClosureEnabled: false,
        roadClosureCount: 0,
        brakeStopEnabled: true,
        brakeStopCount: 2,
        brakeStopTimeMs: 2400,
        stageCount: 3,
        difficultyMultiplier: 1.45
    },
    13: {
        level: 13,
        carSpeed: 100,
        mapRotation: 270,
        pathLength: 7,
        decisionTimeMs: 2800,
        pathFadeEnabled: true,
        pathFadeDelayMs: 2000,
        pathFadeDurationMs: 3000,
        pathFadeInterval: 0,
        roadClosureEnabled: false,
        roadClosureCount: 0,
        brakeStopEnabled: true,
        brakeStopCount: 2,
        brakeStopTimeMs: 2300,
        stageCount: 3,
        difficultyMultiplier: 1.5
    },
    14: {
        level: 14,
        carSpeed: 105,
        mapRotation: 90,
        pathLength: 7,
        decisionTimeMs: 2700,
        pathFadeEnabled: true,
        pathFadeDelayMs: 2000,
        pathFadeDurationMs: 2500,
        pathFadeInterval: 5000,
        roadClosureEnabled: false,
        roadClosureCount: 0,
        brakeStopEnabled: true,
        brakeStopCount: 2,
        brakeStopTimeMs: 2200,
        stageCount: 3,
        difficultyMultiplier: 1.55
    },
    15: {
        level: 15,
        carSpeed: 110,
        mapRotation: 180,
        pathLength: 8,
        decisionTimeMs: 2500,
        pathFadeEnabled: true,
        pathFadeDelayMs: 1500,
        pathFadeDurationMs: 3000,
        pathFadeInterval: 5000,
        roadClosureEnabled: false,
        roadClosureCount: 0,
        brakeStopEnabled: true,
        brakeStopCount: 2,
        brakeStopTimeMs: 2200,
        stageCount: 3,
        difficultyMultiplier: 1.6
    },

    // === CHAPTER 5: ROAD CLOSURES (Levels 16-20) ===
    // Bottom to top, with dynamic route changes
    16: {
        level: 16,
        carSpeed: 90,
        mapRotation: 0,
        pathLength: 6,
        decisionTimeMs: 3500,
        pathFadeEnabled: false,
        pathFadeDelayMs: 0,
        pathFadeDurationMs: 0,
        pathFadeInterval: 0,
        roadClosureEnabled: true,
        roadClosureCount: 1,
        brakeStopEnabled: true,
        brakeStopCount: 2,
        brakeStopTimeMs: 2500,
        stageCount: 3,
        difficultyMultiplier: 1.55
    },
    17: {
        level: 17,
        carSpeed: 95,
        mapRotation: 0,
        pathLength: 7,
        decisionTimeMs: 3200,
        pathFadeEnabled: false,
        pathFadeDelayMs: 0,
        pathFadeDurationMs: 0,
        pathFadeInterval: 0,
        roadClosureEnabled: true,
        roadClosureCount: 1,
        brakeStopEnabled: true,
        brakeStopCount: 2,
        brakeStopTimeMs: 2400,
        stageCount: 3,
        difficultyMultiplier: 1.6
    },
    18: {
        level: 18,
        carSpeed: 100,
        mapRotation: 0,
        pathLength: 7,
        decisionTimeMs: 3000,
        pathFadeEnabled: false,
        pathFadeDelayMs: 0,
        pathFadeDurationMs: 0,
        pathFadeInterval: 0,
        roadClosureEnabled: true,
        roadClosureCount: 2,
        brakeStopEnabled: true,
        brakeStopCount: 2,
        brakeStopTimeMs: 2300,
        stageCount: 3,
        difficultyMultiplier: 1.65
    },
    19: {
        level: 19,
        carSpeed: 105,
        mapRotation: 0,
        pathLength: 8,
        decisionTimeMs: 2800,
        pathFadeEnabled: false,
        pathFadeDelayMs: 0,
        pathFadeDurationMs: 0,
        pathFadeInterval: 0,
        roadClosureEnabled: true,
        roadClosureCount: 2,
        brakeStopEnabled: true,
        brakeStopCount: 3,
        brakeStopTimeMs: 2200,
        stageCount: 4,
        difficultyMultiplier: 1.7
    },
    20: {
        level: 20,
        carSpeed: 110,
        mapRotation: 0,
        pathLength: 8,
        decisionTimeMs: 2600,
        pathFadeEnabled: false,
        pathFadeDelayMs: 0,
        pathFadeDurationMs: 0,
        pathFadeInterval: 0,
        roadClosureEnabled: true,
        roadClosureCount: 3,
        brakeStopEnabled: true,
        brakeStopCount: 3,
        brakeStopTimeMs: 2000,
        stageCount: 4,
        difficultyMultiplier: 1.75
    },

    // === CHAPTER 6: COMBINED MECHANICS (Levels 21-28) ===
    21: {
        level: 21,
        carSpeed: 100,
        mapRotation: 90,
        pathLength: 7,
        decisionTimeMs: 3000,
        pathFadeEnabled: true,
        pathFadeDelayMs: 4000,
        pathFadeDurationMs: 2000,
        pathFadeInterval: 0,
        roadClosureEnabled: true,
        roadClosureCount: 1,
        brakeStopEnabled: true,
        brakeStopCount: 2,
        brakeStopTimeMs: 2200,
        stageCount: 4,
        swapControls: true,
        difficultyMultiplier: 1.75
    },
    22: {
        level: 22,
        carSpeed: 105,
        mapRotation: 180,
        pathLength: 7,
        decisionTimeMs: 2800,
        pathFadeEnabled: true,
        pathFadeDelayMs: 3500,
        pathFadeDurationMs: 2500,
        pathFadeInterval: 0,
        roadClosureEnabled: true,
        roadClosureCount: 1,
        brakeStopEnabled: true,
        brakeStopCount: 2,
        brakeStopTimeMs: 2100,
        stageCount: 4,
        swapControls: true,
        difficultyMultiplier: 1.8
    },
    23: {
        level: 23,
        carSpeed: 110,
        mapRotation: 270,
        pathLength: 8,
        decisionTimeMs: 2700,
        pathFadeEnabled: true,
        pathFadeDelayMs: 3000,
        pathFadeDurationMs: 2500,
        pathFadeInterval: 6000,
        roadClosureEnabled: true,
        roadClosureCount: 1,
        brakeStopEnabled: true,
        brakeStopCount: 2,
        brakeStopTimeMs: 2000,
        stageCount: 4,
        swapControls: true,
        difficultyMultiplier: 1.85
    },
    24: {
        level: 24,
        carSpeed: 115,
        mapRotation: 90,
        pathLength: 8,
        decisionTimeMs: 2600,
        pathFadeEnabled: true,
        pathFadeDelayMs: 2500,
        pathFadeDurationMs: 3000,
        pathFadeInterval: 5500,
        roadClosureEnabled: true,
        roadClosureCount: 2,
        brakeStopEnabled: true,
        brakeStopCount: 3,
        brakeStopTimeMs: 2000,
        stageCount: 4,
        swapControls: true,
        difficultyMultiplier: 1.9
    },
    25: {
        level: 25,
        carSpeed: 120,
        mapRotation: 180,
        pathLength: 9,
        decisionTimeMs: 2500,
        pathFadeEnabled: true,
        pathFadeDelayMs: 2500,
        pathFadeDurationMs: 2500,
        pathFadeInterval: 5000,
        roadClosureEnabled: true,
        roadClosureCount: 2,
        brakeStopEnabled: true,
        brakeStopCount: 3,
        brakeStopTimeMs: 1900,
        stageCount: 4,
        swapControls: true,
        difficultyMultiplier: 1.95
    },
    26: {
        level: 26,
        carSpeed: 125,
        mapRotation: 270,
        pathLength: 9,
        decisionTimeMs: 2400,
        pathFadeEnabled: true,
        pathFadeDelayMs: 2000,
        pathFadeDurationMs: 3000,
        pathFadeInterval: 5000,
        roadClosureEnabled: true,
        roadClosureCount: 2,
        brakeStopEnabled: true,
        brakeStopCount: 3,
        brakeStopTimeMs: 1900,
        stageCount: 4,
        swapControls: true,
        difficultyMultiplier: 2.0
    },
    27: {
        level: 27,
        carSpeed: 130,
        mapRotation: 90,
        pathLength: 9,
        decisionTimeMs: 2300,
        pathFadeEnabled: true,
        pathFadeDelayMs: 2000,
        pathFadeDurationMs: 3000,
        pathFadeInterval: 4500,
        roadClosureEnabled: true,
        roadClosureCount: 2,
        brakeStopEnabled: true,
        brakeStopCount: 3,
        brakeStopTimeMs: 1800,
        stageCount: 4,
        swapControls: true,
        difficultyMultiplier: 2.05
    },
    28: {
        level: 28,
        carSpeed: 135,
        mapRotation: 180,
        pathLength: 10,
        decisionTimeMs: 2200,
        pathFadeEnabled: true,
        pathFadeDelayMs: 1500,
        pathFadeDurationMs: 3500,
        pathFadeInterval: 4500,
        roadClosureEnabled: true,
        roadClosureCount: 2,
        brakeStopEnabled: true,
        brakeStopCount: 3,
        brakeStopTimeMs: 1800,
        stageCount: 4,
        swapControls: true,
        difficultyMultiplier: 2.1
    },

    // === CHAPTER 7: MASTERY (Levels 29-35) ===
    29: {
        level: 29,
        carSpeed: 140,
        mapRotation: 270,
        pathLength: 10,
        decisionTimeMs: 2200,
        pathFadeEnabled: true,
        pathFadeDelayMs: 1500,
        pathFadeDurationMs: 3500,
        pathFadeInterval: 4000,
        roadClosureEnabled: true,
        roadClosureCount: 3,
        brakeStopEnabled: true,
        brakeStopCount: 3,
        brakeStopTimeMs: 1800,
        stageCount: 5,
        swapControls: true,
        difficultyMultiplier: 2.15
    },
    30: {
        level: 30,
        carSpeed: 145,
        mapRotation: 90,
        pathLength: 10,
        decisionTimeMs: 2100,
        pathFadeEnabled: true,
        pathFadeDelayMs: 1500,
        pathFadeDurationMs: 3500,
        pathFadeInterval: 4000,
        roadClosureEnabled: true,
        roadClosureCount: 3,
        brakeStopEnabled: true,
        brakeStopCount: 3,
        brakeStopTimeMs: 1700,
        stageCount: 5,
        swapControls: true,
        difficultyMultiplier: 2.2
    },
    31: {
        level: 31,
        carSpeed: 150,
        mapRotation: 180,
        pathLength: 11,
        decisionTimeMs: 2000,
        pathFadeEnabled: true,
        pathFadeDelayMs: 1500,
        pathFadeDurationMs: 3000,
        pathFadeInterval: 3500,
        roadClosureEnabled: true,
        roadClosureCount: 3,
        brakeStopEnabled: true,
        brakeStopCount: 4,
        brakeStopTimeMs: 1700,
        stageCount: 5,
        swapControls: true,
        difficultyMultiplier: 2.25
    },
    32: {
        level: 32,
        carSpeed: 155,
        mapRotation: 270,
        pathLength: 11,
        decisionTimeMs: 2000,
        pathFadeEnabled: true,
        pathFadeDelayMs: 1000,
        pathFadeDurationMs: 3500,
        pathFadeInterval: 3500,
        roadClosureEnabled: true,
        roadClosureCount: 3,
        brakeStopEnabled: true,
        brakeStopCount: 4,
        brakeStopTimeMs: 1600,
        stageCount: 5,
        swapControls: true,
        difficultyMultiplier: 2.3
    },
    33: {
        level: 33,
        carSpeed: 160,
        mapRotation: 90,
        pathLength: 12,
        decisionTimeMs: 1900,
        pathFadeEnabled: true,
        pathFadeDelayMs: 1000,
        pathFadeDurationMs: 4000,
        pathFadeInterval: 3000,
        roadClosureEnabled: true,
        roadClosureCount: 3,
        brakeStopEnabled: true,
        brakeStopCount: 4,
        brakeStopTimeMs: 1600,
        stageCount: 5,
        swapControls: true,
        difficultyMultiplier: 2.35
    },
    34: {
        level: 34,
        carSpeed: 165,
        mapRotation: 180,
        pathLength: 12,
        decisionTimeMs: 1800,
        pathFadeEnabled: true,
        pathFadeDelayMs: 1000,
        pathFadeDurationMs: 4000,
        pathFadeInterval: 3000,
        roadClosureEnabled: true,
        roadClosureCount: 4,
        brakeStopEnabled: true,
        brakeStopCount: 4,
        brakeStopTimeMs: 1500,
        stageCount: 5,
        swapControls: true,
        difficultyMultiplier: 2.4
    },
    35: {
        level: 35,
        carSpeed: 170,
        mapRotation: 270,
        pathLength: 13,
        decisionTimeMs: 1700,
        pathFadeEnabled: true,
        pathFadeDelayMs: 800,
        pathFadeDurationMs: 4000,
        pathFadeInterval: 2500,
        roadClosureEnabled: true,
        roadClosureCount: 4,
        brakeStopEnabled: true,
        brakeStopCount: 4,
        brakeStopTimeMs: 1500,
        stageCount: 5,
        swapControls: true,
        difficultyMultiplier: 2.5
    }
};
