import type { PinkCupLevelConfig } from './types';

/**
 * Find the Pink Cup - Level Configurations
 * Scalable system with extensible parameters
 */

export const PINKCUP_LEVELS: Record<number, PinkCupLevelConfig> = {
  // ===== LEVELS 1-5: STARTER =====
  // No probes, fewer numbers
  1: {
    level: 1,
    gridCols: 3,
    gridRows: 3,
    numberedTilesCount: 1,
    revealDurationMs: 2000,
    timeLimitSeconds: 120,
    parTimeSeconds: 60,
    memoryType: 'number',
    probeType: 'single_cell',
    probeCount: 0,
    showProbeImmediately: false,
    difficultyMultiplier: 0.8,
    mode: 'classic'
  },
  2: {
    level: 2,
    gridCols: 3,
    gridRows: 3,
    numberedTilesCount: 2,
    revealDurationMs: 1900,
    timeLimitSeconds: 110,
    parTimeSeconds: 55,
    memoryType: 'number',
    probeType: 'single_cell',
    probeCount: 0,
    showProbeImmediately: false,
    difficultyMultiplier: 0.85,
    mode: 'classic'
  },
  3: {
    level: 3,
    gridCols: 3,
    gridRows: 3,
    numberedTilesCount: 2,
    revealDurationMs: 1800,
    timeLimitSeconds: 100,
    parTimeSeconds: 50,
    memoryType: 'number',
    probeType: 'single_cell',
    probeCount: 0,
    showProbeImmediately: false,
    difficultyMultiplier: 0.9,
    mode: 'classic'
  },
  4: {
    level: 4,
    gridCols: 3,
    gridRows: 3,
    numberedTilesCount: 2,
    revealDurationMs: 1700,
    timeLimitSeconds: 95,
    parTimeSeconds: 48,
    memoryType: 'number',
    probeType: 'single_cell',
    probeCount: 0,
    showProbeImmediately: false,
    difficultyMultiplier: 0.95,
    mode: 'classic'
  },
  5: {
    level: 5,
    gridCols: 3,
    gridRows: 3,
    numberedTilesCount: 2,
    revealDurationMs: 1600,
    timeLimitSeconds: 90,
    parTimeSeconds: 45,
    memoryType: 'number',
    probeType: 'single_cell',
    probeCount: 0,
    showProbeImmediately: false,
    difficultyMultiplier: 1.0,
    mode: 'classic'
  },

  // ===== LEVELS 6-10: EARLY =====
  // 1 probe, more numbers
  6: {
    level: 6,
    gridCols: 3,
    gridRows: 3,
    numberedTilesCount: 2,
    revealDurationMs: 1500,
    timeLimitSeconds: 85,
    parTimeSeconds: 42,
    memoryType: 'number',
    probeType: 'single_cell',
    probeCount: 1,
    showProbeImmediately: true,
    difficultyMultiplier: 1.05,
    mode: 'classic'
  },
  7: {
    level: 7,
    gridCols: 3,
    gridRows: 3,
    numberedTilesCount: 2,
    revealDurationMs: 1450,
    timeLimitSeconds: 80,
    parTimeSeconds: 40,
    memoryType: 'number',
    probeType: 'single_cell',
    probeCount: 1,
    showProbeImmediately: true,
    difficultyMultiplier: 1.1,
    mode: 'classic'
  },
  8: {
    level: 8,
    gridCols: 3,
    gridRows: 3,
    numberedTilesCount: 3,
    revealDurationMs: 1400,
    timeLimitSeconds: 75,
    parTimeSeconds: 38,
    memoryType: 'number',
    probeType: 'single_cell',
    probeCount: 1,
    showProbeImmediately: true,
    difficultyMultiplier: 1.15,
    mode: 'classic'
  },
  9: {
    level: 9,
    gridCols: 3,
    gridRows: 3,
    numberedTilesCount: 3,
    revealDurationMs: 1350,
    timeLimitSeconds: 70,
    parTimeSeconds: 35,
    memoryType: 'number',
    probeType: 'single_cell',
    probeCount: 1,
    showProbeImmediately: true,
    difficultyMultiplier: 1.2,
    mode: 'classic'
  },
  10: {
    level: 10,
    gridCols: 3,
    gridRows: 3,
    numberedTilesCount: 3,
    revealDurationMs: 1300,
    timeLimitSeconds: 65,
    parTimeSeconds: 33,
    memoryType: 'number',
    probeType: 'single_cell',
    probeCount: 1,
    showProbeImmediately: true,
    difficultyMultiplier: 1.25,
    mode: 'classic'
  },

  // ===== LEVELS 11-15: MID =====
  // 2 probes, tighter time
  11: {
    level: 11,
    gridCols: 3,
    gridRows: 3,
    numberedTilesCount: 3,
    revealDurationMs: 1200,
    timeLimitSeconds: 60,
    parTimeSeconds: 30,
    memoryType: 'number',
    probeType: 'single_cell',
    probeCount: 2,
    showProbeImmediately: true,
    difficultyMultiplier: 1.3,
    mode: 'classic'
  },
  12: {
    level: 12,
    gridCols: 3,
    gridRows: 3,
    numberedTilesCount: 3,
    revealDurationMs: 1150,
    timeLimitSeconds: 55,
    parTimeSeconds: 28,
    memoryType: 'number',
    probeType: 'single_cell',
    probeCount: 2,
    showProbeImmediately: true,
    difficultyMultiplier: 1.35,
    mode: 'classic'
  },
  13: {
    level: 13,
    gridCols: 3,
    gridRows: 3,
    numberedTilesCount: 3,
    revealDurationMs: 1100,
    timeLimitSeconds: 50,
    parTimeSeconds: 25,
    memoryType: 'number',
    probeType: 'single_cell',
    probeCount: 2,
    showProbeImmediately: true,
    difficultyMultiplier: 1.4,
    mode: 'classic'
  },
  14: {
    level: 14,
    gridCols: 3,
    gridRows: 3,
    numberedTilesCount: 4,
    revealDurationMs: 1050,
    timeLimitSeconds: 45,
    parTimeSeconds: 23,
    memoryType: 'number',
    probeType: 'single_cell',
    probeCount: 2,
    showProbeImmediately: true,
    difficultyMultiplier: 1.45,
    mode: 'classic'
  },
  15: {
    level: 15,
    gridCols: 3,
    gridRows: 3,
    numberedTilesCount: 4,
    revealDurationMs: 1000,
    timeLimitSeconds: 40,
    parTimeSeconds: 20,
    memoryType: 'number',
    probeType: 'single_cell',
    probeCount: 2,
    showProbeImmediately: true,
    difficultyMultiplier: 1.5,
    mode: 'classic'
  },

  // ===== LEVELS 16-20: ADVANCED =====
  // 4x4 grid, more probes
  16: {
    level: 16,
    gridCols: 4,
    gridRows: 4,
    numberedTilesCount: 4,
    revealDurationMs: 1600,
    timeLimitSeconds: 120,
    parTimeSeconds: 60,
    memoryType: 'number',
    probeType: 'single_cell',
    probeCount: 2,
    showProbeImmediately: true,
    difficultyMultiplier: 1.3,
    mode: 'classic'
  },
  17: {
    level: 17,
    gridCols: 4,
    gridRows: 4,
    numberedTilesCount: 4,
    revealDurationMs: 1500,
    timeLimitSeconds: 110,
    parTimeSeconds: 55,
    memoryType: 'number',
    probeType: 'single_cell',
    probeCount: 2,
    showProbeImmediately: true,
    difficultyMultiplier: 1.4,
    mode: 'classic'
  },
  18: {
    level: 18,
    gridCols: 4,
    gridRows: 4,
    numberedTilesCount: 4,
    revealDurationMs: 1400,
    timeLimitSeconds: 100,
    parTimeSeconds: 50,
    memoryType: 'number',
    probeType: 'single_cell',
    probeCount: 2,
    showProbeImmediately: true,
    difficultyMultiplier: 1.5,
    mode: 'memory_focus'
  },
  19: {
    level: 19,
    gridCols: 4,
    gridRows: 4,
    numberedTilesCount: 4,
    revealDurationMs: 1300,
    timeLimitSeconds: 90,
    parTimeSeconds: 45,
    memoryType: 'number',
    probeType: 'multiple_cells',
    probeCount: 3,
    showProbeImmediately: true,
    difficultyMultiplier: 1.6,
    mode: 'memory_focus'
  },
  20: {
    level: 20,
    gridCols: 4,
    gridRows: 4,
    numberedTilesCount: 5,
    revealDurationMs: 1200,
    timeLimitSeconds: 80,
    parTimeSeconds: 40,
    memoryType: 'number',
    probeType: 'multiple_cells',
    probeCount: 3,
    showProbeImmediately: true,
    difficultyMultiplier: 1.7,
    mode: 'memory_focus'
  },

  // ===== LEVELS 21-25: EXPERT =====
  // 5x5 grid, heavier memory load
  21: {
    level: 21,
    gridCols: 5,
    gridRows: 5,
    numberedTilesCount: 5,
    revealDurationMs: 1500,
    timeLimitSeconds: 140,
    parTimeSeconds: 70,
    memoryType: 'number',
    probeType: 'multiple_cells',
    probeCount: 3,
    showProbeImmediately: true,
    difficultyMultiplier: 1.8,
    mode: 'memory_focus'
  },
  22: {
    level: 22,
    gridCols: 5,
    gridRows: 5,
    numberedTilesCount: 5,
    revealDurationMs: 1400,
    timeLimitSeconds: 130,
    parTimeSeconds: 65,
    memoryType: 'number',
    probeType: 'multiple_cells',
    probeCount: 3,
    showProbeImmediately: true,
    difficultyMultiplier: 1.9,
    mode: 'memory_focus'
  },
  23: {
    level: 23,
    gridCols: 5,
    gridRows: 5,
    numberedTilesCount: 5,
    revealDurationMs: 1300,
    timeLimitSeconds: 120,
    parTimeSeconds: 60,
    memoryType: 'number',
    probeType: 'multiple_cells',
    probeCount: 3,
    showProbeImmediately: true,
    difficultyMultiplier: 2.0,
    mode: 'memory_focus'
  },
  24: {
    level: 24,
    gridCols: 5,
    gridRows: 5,
    numberedTilesCount: 5,
    revealDurationMs: 1200,
    timeLimitSeconds: 110,
    parTimeSeconds: 55,
    memoryType: 'number',
    probeType: 'multiple_cells',
    probeCount: 3,
    showProbeImmediately: true,
    difficultyMultiplier: 2.1,
    mode: 'memory_focus'
  },
  25: {
    level: 25,
    gridCols: 5,
    gridRows: 5,
    numberedTilesCount: 5,
    revealDurationMs: 1100,
    timeLimitSeconds: 100,
    parTimeSeconds: 50,
    memoryType: 'number',
    probeType: 'multiple_cells',
    probeCount: 3,
    showProbeImmediately: true,
    difficultyMultiplier: 2.2,
    mode: 'memory_focus'
  },

  // ===== LEVELS 26-30: CHALLENGE =====
  // 5x5 grid, time attack pacing
  26: {
    level: 26,
    gridCols: 5,
    gridRows: 5,
    numberedTilesCount: 5,
    revealDurationMs: 1000,
    timeLimitSeconds: 90,
    parTimeSeconds: 45,
    memoryType: 'number',
    probeType: 'multiple_cells',
    probeCount: 3,
    showProbeImmediately: true,
    difficultyMultiplier: 2.3,
    mode: 'time_attack'
  },
  27: {
    level: 27,
    gridCols: 5,
    gridRows: 5,
    numberedTilesCount: 5,
    revealDurationMs: 950,
    timeLimitSeconds: 80,
    parTimeSeconds: 40,
    memoryType: 'number',
    probeType: 'multiple_cells',
    probeCount: 3,
    showProbeImmediately: true,
    difficultyMultiplier: 2.4,
    mode: 'time_attack'
  },
  28: {
    level: 28,
    gridCols: 5,
    gridRows: 5,
    numberedTilesCount: 5,
    revealDurationMs: 900,
    timeLimitSeconds: 70,
    parTimeSeconds: 35,
    memoryType: 'number',
    probeType: 'multiple_cells',
    probeCount: 3,
    showProbeImmediately: true,
    difficultyMultiplier: 2.5,
    mode: 'time_attack'
  },
  29: {
    level: 29,
    gridCols: 5,
    gridRows: 5,
    numberedTilesCount: 5,
    revealDurationMs: 850,
    timeLimitSeconds: 60,
    parTimeSeconds: 30,
    memoryType: 'number',
    probeType: 'multiple_cells',
    probeCount: 3,
    showProbeImmediately: true,
    difficultyMultiplier: 2.6,
    mode: 'time_attack'
  },
  30: {
    level: 30,
    gridCols: 5,
    gridRows: 5,
    numberedTilesCount: 5,
    revealDurationMs: 800,
    timeLimitSeconds: 50,
    parTimeSeconds: 25,
    memoryType: 'number',
    probeType: 'multiple_cells',
    probeCount: 4,
    showProbeImmediately: true,
    difficultyMultiplier: 2.7,
    mode: 'time_attack'
  }
};

/**
 * Helper function to get level config with fallback
 */
export function getPinkCupLevel(level: number): PinkCupLevelConfig {
  return PINKCUP_LEVELS[level] || PINKCUP_LEVELS[1];
}
